export const MENUS_LOADING = 'MENUS_LOADING';
export const ADD_MENUS = 'ADD_MENUS';
export const MENUS_FAILED = 'MENUS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const ADD_SERVICES = 'ADD_SERVICES';
export const SERVICES_FAILED = 'SERVICES_FAILED';
export const SERVICES_LOADING = 'SERVICES_LOADING';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const LIKE_MENU = 'LIKE_MENU';
