export const MENUS_LOADING = 'MENUS_LOADING';
export const ADD_MENUS = 'ADD_MENUS';
export const MENUS_FAILED = 'MENUS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELECT_FAVORITE = 'DELETE_FAVORITE';